### ISSUE TITLE
Add landing page for powertools.

### ISSUE THREAD

**Issue by EmCeeEs** [hardforkio/homepage#364]
The page should be hosted at `https://hardfork.io/powertools`.

**Specs**
- [x] List and describe (upcoming) features
- [x] List and describe (upcoming) similar extensions
- [x] List and describe supported browser (see #366)
- [x] Link to chrome extension https://chrome.google.com/webstore/detail/hardfork-powertools/ocfgkhnplliadmaifkhhjncimaobcchh?hl=de&authuser=1 (see #366)
- [x] Use official logo https://github.com/hardforkio/powertools/issues/86 (see #366)
- [x] Offer user feedback via freshchat (see #367)

**Comment by EmCeeEs** [comment]
fixed by #366
